name: Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1' # Weekly on Monday

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: QuickCart/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: QuickCart

      - name: Run security audit
        run: npm audit --audit-level moderate
        working-directory: QuickCart

      - name: Run npm audit fix
        run: npm audit fix
        working-directory: QuickCart

      - name: Check for outdated packages
        run: npm outdated || true
        working-directory: QuickCart
